apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
webhooks:
  - name: webhook.default.svc
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1","v1beta1"]
    rules:
      - apiGroups: ["apps", ""]
        resources: ["deployments"]
        apiVersions:
          - "*"
        operations: ["CREATE", "UPDATE"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: webhook
        namespace: default
        path: /webhook/
      caBundle: SHOULD BE IN BASE64
